"""create reservations table

Revision ID: 7249af207641
Revises: dbe34ea2e679
Create Date: 2023-05-17 15:10:23.743713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7249af207641'
down_revision = 'dbe34ea2e679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('no_of_tickets', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('no_of_tickets >= 0', name='no_of_tickets_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
