version: "3.4"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "flask db upgrade head && flask run --host 0.0.0.0 --debug"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  pgdata:
